CREATE TABLE ss.rds_databases_schedules (
    db_resource_id      varchar(40),
    db_identifier       varchar(40) ,
    db_tag_name         varchar(40),
    date_created_on     varchar(40) ,
	db_instance_type	varchar(40),
    db_engine           varchar(40) ,
    db_state            varchar(40) ,
    db_storage_type     varchar(40) ,
	db_storage_size     int,
	total_paid          int,
	account_id          varchar(40) ,
    account_name        varchar(40) ,
    region              varchar(40),
	tag_value_1         varchar(40),
	tag_value_2         varchar(40),
	tag_value_3         varchar(40),
    tag_value_4         varchar(40),
    hourly_price        varchar(40),
    mon_str_time        varchar(40),
	mon_stp_time        varchar(40),
    tue_str_time        varchar(40),
	tue_stp_time        varchar(40),
    wed_str_time        varchar(40),
	wed_stp_time        varchar(40),
    thu_str_time        varchar(40),
	thu_stp_time        varchar(40),
	fri_stp_time        varchar(40),
    fri_str_time        varchar(40),
    sat_str_time        varchar(40),
	sat_stp_time        varchar(40),
    sun_str_time        varchar(40),
    sun_stp_time        varchar(40),
    stack_arn           varchar(40),
    rds_group_name      varchar(40),
    auto_stop_enable    varchar(40), 
    is_statefull_set    varchar(40),
	statefull_set_name  varchar(40),
	statefull_set_arn   varchar(150),
    enable_schedules    varchar(10),
    PRIMARY KEY(db_resource_id),
    CONSTRAINT fk_account_id
      FOREIGN KEY(account_id) 
	  REFERENCES ad.aws_accounts(account_id)
	  ON DELETE CASCADE
);
